# Generated by Django 5.2.8 on 2025-11-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_notification'),
        ('finance', '0001_initial'),
        ('vehicles', '0002_add_handled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bãi đỗ xe')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('capacity', models.PositiveIntegerField(verbose_name='Sức chứa')),
                ('available_slots', models.PositiveIntegerField(verbose_name='Chỗ trống hiện tại')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Vị trí')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('maintenance', 'Bảo trì'), ('closed', 'Đóng cửa')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá theo giờ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
                'verbose_name': 'Bãi đỗ xe',
                'verbose_name_plural': 'Bãi đỗ xe',
            },
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(verbose_name='Thời gian vào')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian ra')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Phí gửi xe')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_records', to='cards.card')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_records', to='parking.parkinglot')),
                ('parking_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_records', to='finance.parkingrate')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_records', to='vehicles.vehicle')),
            ],
            options={
                'managed': False,
                'verbose_name': 'Lượt gửi xe',
                'verbose_name_plural': 'Lượt gửi xe',
            },
        ),

        # Now create ParkingSlot (this will create the actual table)
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=20, verbose_name='Số vị trí')),
                ('slot_type', models.CharField(choices=[('car', 'Ô tô'), ('motorcycle', 'Xe máy'), ('bicycle', 'Xe đạp'), ('disabled', 'Người khuyết tật'), ('vip', 'VIP')], default='car', max_length=20, verbose_name='Loại vị trí')),
                ('status', models.CharField(choices=[('available', 'Trống'), ('occupied', 'Đã có xe'), ('reserved', 'Đã đặt chỗ'), ('maintenance', 'Bảo trì')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='Tầng')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Khu vực')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkinglot')),
            ],
            options={
                'verbose_name': 'Vị trí đỗ xe',
                'verbose_name_plural': 'Vị trí đỗ xe',
                'unique_together': {('parking_lot', 'slot_number')},
            },
        ),
    ]
