# Generated by Django 5.2.8 on 2025-11-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Ô tô'), ('motorcycle', 'Xe máy'), ('bicycle', 'Xe đạp')], max_length=20)),
                ('package_type', models.CharField(choices=[('monthly', 'Vé tháng'), ('hourly', 'Vé theo lượt')], max_length=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình giá',
                'verbose_name_plural': 'Cấu hình giá',
                'unique_together': {('vehicle_type', 'package_type')},
            },
        ),
    ]
