# Generated by Django 5.2.7 on 2025-11-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_pricingsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'verbose_name': 'Bãi đỗ xe', 'verbose_name_plural': 'Bãi đỗ xe'},
        ),
        migrations.AlterModelOptions(
            name='parkingrecord',
            options={'verbose_name': 'Lượt gửi xe', 'verbose_name_plural': 'Lượt gửi xe'},
        ),
    ]
