# Generated by Django 5.2.7 on 2025-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_add_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='allowed_vehicle_types',
            field=models.CharField(choices=[('small', 'Xe nhỏ (Xe máy, Xe đạp)'), ('large', 'Xe to (Ô tô, Xe tải, Taxi)'), ('all', 'Tất cả loại xe')], default='all', max_length=20, verbose_name='Loại xe được phép'),
        ),
    ]
