# Generated by Django 5.2.7 on 2025-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Ô tô'), ('motorcycle', 'Xe máy'), ('bicycle', 'Xe đạp'), ('truck', 'Xe tải'), ('taxi', 'Taxi')], max_length=20, verbose_name='Loại xe')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá theo giờ')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá theo ngày')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá theo tháng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bảng giá',
                'verbose_name_plural': 'Bảng giá',
            },
        ),
    ]
