# Generated by Django 5.2.8 on 2025-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Xe máy', 'Xe máy'), ('Ô tô', 'Ô tô'), ('Xe đạp', 'Xe đạp')], max_length=20, verbose_name='Loại xe')),
                ('customer_type', models.CharField(choices=[('Khách gửi tháng', 'Khách gửi tháng'), ('Khách vãng lai', 'Khách vãng lai')], max_length=20, verbose_name='Loại khách hàng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá (VNĐ)')),
                ('unit', models.CharField(default='VNĐ', max_length=20, verbose_name='Đơn vị')),
                ('duration', models.CharField(help_text='Ví dụ: /tháng, /lượt', max_length=50, verbose_name='Thời gian')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bảng giá dịch vụ',
                'verbose_name_plural': 'Bảng giá dịch vụ',
                'unique_together': {('vehicle_type', 'customer_type')},
            },
        ),
    ]
