# Generated by Django 5.2.6 on 2025-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('nhanvien', 'Nhân viên giữ xe')], default='nhanvien', max_length=20, verbose_name='Vai trò'),
        ),
    ]
