# Generated by Django 5.2.7 on 2025-10-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_users_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác thực'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác thực'), ('approved', 'Đã xác thực'), ('rejected', 'Từ chối')], default='approved', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('nhanvien', 'Nhân viên giữ xe'), ('khachhang', 'Khách hàng')], default='khachhang', max_length=20, verbose_name='Vai trò'),
        ),
    ]
