# Generated by Django 5.2.7 on 2025-11-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('nhanvien', 'Nhân viên giữ xe'), ('khachhang', 'Khách hàng')], default='khachhang', max_length=20, verbose_name='Vai trò'),
        ),
    ]
