# Generated by Django 5.2.8 on 2025-11-07 18:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Lương cơ bản')),
                ('total_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tổng lương')),
                ('withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Đã rút')),
                ('available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Có thể rút')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lương nhân viên',
                'verbose_name_plural': 'Lương nhân viên',
            },
        ),
        migrations.CreateModel(
            name='SalaryWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền rút')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do rút lương')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian yêu cầu')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdraws', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu rút lương',
                'verbose_name_plural': 'Yêu cầu rút lương',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=8, max_digits=4, verbose_name='Thời gian làm (giờ)')),
                ('status', models.CharField(choices=[('working', 'Đang làm việc'), ('finished', 'Đã hoàn thành'), ('interrupted', 'Bị gián đoạn')], default='working', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'ordering': ['-start_time'],
            },
        ),
    ]
