# Generated by Django 5.2.8 on 2025-11-09 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_salary_salarywithdraw_workshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền thanh toán')),
                ('shifts_count', models.IntegerField(default=0, verbose_name='Số ca làm')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thanh toán lương',
                'verbose_name_plural': 'Thanh toán lương',
                'ordering': ['-payment_date'],
            },
        ),
    ]
