# Generated by Django 5.2.8 on 2025-11-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_salarypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='status',
            field=models.CharField(choices=[('working', 'Đang làm việc'), ('finished', 'Đã hoàn thành'), ('interrupted', 'Bị gián đoạn'), ('paid', 'Đã thanh toán')], default='working', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
