# Generated by Django 5.2.7 on 2025-10-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('customer_type', models.CharField(choices=[('regular', 'Khách vãng lai'), ('monthly', 'Khách gửi tháng')], default='regular', max_length=20, verbose_name='Loại khách')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
            },
        ),
        migrations.CreateModel(
            name='MonthlySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn hiệu lực')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Đăng ký gửi xe tháng',
                'verbose_name_plural': 'Đăng ký gửi xe tháng',
            },
        ),
    ]
