# Generated by Django 5.2.7 on 2025-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Biển số xe'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('motorbike', 'Xe máy'), ('car', 'Ô tô'), ('bicycle', 'Xe đạp')], max_length=20, null=True, verbose_name='Loại xe'),
        ),
    ]
