# Generated by Django 5.2.7 on 2025-10-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_address_customer_license_plate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Khách vãng lai', 'Khách vãng lai'), ('Khách gửi tháng', 'Khách gửi tháng')], max_length=20, verbose_name='Phân loại khách'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Xe máy', 'Xe máy'), ('Ô tô', 'Ô tô'), ('Xe đạp', 'Xe đạp')], max_length=20, null=True, verbose_name='Loại xe'),
        ),
    ]
