# Generated by Django 5.2.8 on 2025-11-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('not_registered', 'Chưa đăng ký'), ('awaiting_approval', 'Chờ duyệt'), ('approved', 'Đã duyệt')], default='not_registered', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
