# Generated by Django 5.2.7 on 2025-11-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_status'),
        ('customers', '0006_customer_user_delete_vehicle'),
    ]

    operations = [
    ]
