# Generated by Django 5.2.7 on 2025-11-10 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số dư')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='customers.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Ví điện tử',
                'verbose_name_plural': 'Ví điện tử',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdraw', 'Rút tiền'), ('payment', 'Thanh toán'), ('refund', 'Hoàn tiền')], max_length=20, verbose_name='Loại giao dịch')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('balance_before', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số dư trước')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số dư sau')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.wallet', verbose_name='Ví')),
            ],
            options={
                'verbose_name': 'Giao dịch ví',
                'verbose_name_plural': 'Giao dịch ví',
                'ordering': ['-created_at'],
            },
        ),
    ]
