# Generated by Django 5.2.7 on 2025-11-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_wallet_wallettransaction'),
        ('vehicles', '0006_vehicle_parking_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysubscription',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vehicles.vehicle', verbose_name='Xe'),
        ),
    ]
