# Generated by Django 5.2.7 on 2025-11-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Biển số xe')),
                ('vehicle_type', models.CharField(choices=[('car', 'Ô tô'), ('motorcycle', 'Xe máy'), ('bicycle', 'Xe đạp'), ('truck', 'Xe tải'), ('taxi', 'Taxi')], default='car', max_length=20, verbose_name='Loại xe')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Màu xe')),
                ('service_package', models.CharField(choices=[('daily', 'Vé ngày'), ('monthly', 'Vé tháng'), ('guest', 'Vãng lai')], default='guest', max_length=10, verbose_name='Gói dịch vụ')),
                ('parking_slot', models.CharField(blank=True, max_length=30, verbose_name='Vị trí')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Hình ảnh')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian vào')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian ra')),
                ('status', models.CharField(choices=[('in', 'Đang gửi'), ('out', 'Đã rời')], default='in', max_length=5, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Phương tiện',
                'verbose_name_plural': 'Phương tiện',
                'ordering': ['-check_in'],
            },
        ),
    ]
