# Generated by Django 5.2.7 on 2025-11-09 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_add_handled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Đã duyệt'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
    ]
