# Generated by Django 5.2.8 on 2025-11-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='service_package',
            field=models.CharField(choices=[('daily', 'Vé ngày'), ('monthly', 'Vé tháng'), ('guest', 'Vãng lai')], default='monthly', max_length=10, verbose_name='Gói dịch vụ'),
        ),
    ]
