# Generated by Django 5.2.7 on 2025-11-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_approved_vehicle_approved_by'),
        ('vehicles', '0004_change_service_package_default'),
    ]

    operations = [
    ]
