# Generated by Django 5.2.7 on 2025-11-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_add_missing_columns'),
        ('vehicles', '0005_merge_20251109_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='parking.parkinglot', verbose_name='Bãi xe'),
        ),
    ]
