# Generated by Django 5.2.7 on 2025-11-05 16:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_options_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='Mã thẻ')),
                ('card_type', models.CharField(choices=[('rfid', 'RFID'), ('qr', 'QR Code')], max_length=20, verbose_name='Loại thẻ')),
                ('status', models.CharField(choices=[('active', 'Đang sử dụng'), ('lost', 'Mất thẻ'), ('damaged', 'Hỏng'), ('locked', 'Đã khóa')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Ngày cấp')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Thẻ xe',
                'verbose_name_plural': 'Thẻ xe',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Hủy')], default='pending', max_length=12)),
                ('method', models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('momo', 'MOMO')], default='cash', max_length=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_payments', to='vehicles.vehicle')),
            ],
        ),
    ]
