# Generated by Django 5.2.8 on 2025-11-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_paymenttransaction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('awaiting_approval', 'Chờ duyệt'), ('pending', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Hủy')], default='awaiting_approval', max_length=20),
        ),
    ]
