# Generated by Django 5.2.8 on 2025-11-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_change_customer_delete_cascade'),
        ('customers', '0006_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
